export const Types ={
   SET_PRODUCTS:"SET_PRODUCTS",
   GET_ONE_PRODUCT:"GET_ONE_PRODUCT",
   DELETE_ONE_PRODUCT:"DELETE_ONE_PRODUCT",
   SET_CATEGORY_DATA:"SET_CATEGORY_DATA",
   SET_CATEGORY_PRODUCT:"SET_CATEGORY_PRODUCT",
   SET_CART_PRODUCT:"SET_CART_PRODUCT",
    DELETE_ONE_CART_PRODUCT:" DELETE_ONE_CART_PRODUCT",
    INCREMENT_ONE_CART_PRODUCT:"INCREMENT_ONE_CART_PRODUCT",
    ADD_ONE_MORE:"ADD_ONE_MORE",
    REMOVE_ONE:"REMOVE_ONE_MORE"


}